2024-09-03 22:36:32 | INFO    | __main__:stash:131 | run - {'image': '20231121', 'version': '0.10.1.post2', 'role': 'EpicPlayer', 'headless': True}
2024-09-03 22:36:36 | WARNING    | epic_games.agent:get_order_history:467 | Failed to get order history, cookie may have expired - {}
2024-09-03 22:36:36 | DEBUG    | __main__:create_tasks:66 | Put task - {'title': 'Wild Card Football', 'url': 'https://store.epicgames.com/en-US/p/wild-card-football'}
2024-09-03 22:36:36 | DEBUG    | __main__:create_tasks:66 | Put task - {'title': 'Fallout® Classic Collection', 'url': 'https://store.epicgames.com/en-US/bundles/fallout-classic-collection'}
2024-09-03 22:36:41 | INFO    | epic_games.agent:claim_weekly_games:294 | claim_weekly_games - {'action': 'go to store', 'url': 'https://store.epicgames.com/en-US/p/wild-card-football'}
2024-09-03 22:36:54 | ERROR    | __main__:run:158 | An error has been caught in function 'run', process 'MainProcess' (3779), thread 'MainThread' (139754628545408): - {}
Traceback (most recent call last):
  File "/home/runner/work/Epic_Auto/Epic_Auto/epic/src/claim.py", line 162, in <module>
    asyncio.run(run())
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/home/runner/work/Epic_Auto/Epic_Auto/epic/src/claim.py", line 158, in run
    await agent.stash()
  File "/home/runner/work/Epic_Auto/Epic_Auto/epic/src/claim.py", line 151, in stash
    await self.claim_epic_games(context)
  File "/home/runner/work/Epic_Auto/Epic_Auto/epic/src/claim.py", line 122, in claim_epic_games
    await epic.claim_weekly_games(page, single_promotions)
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/tenacity/asyncio/__init__.py", line 189, in async_wrapped
    return await copy(fn, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/tenacity/asyncio/__init__.py", line 111, in __call__
    do = await self.iter(retry_state=retry_state)
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/tenacity/asyncio/__init__.py", line 153, in iter
    result = await action(retry_state)
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/tenacity/_utils.py", line 99, in inner
    return call(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/tenacity/__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/tenacity/asyncio/__init__.py", line 114, in __call__
    result = await fn(*args, **kwargs)
  File "/home/runner/work/Epic_Auto/Epic_Auto/epic/src/epic_games/agent.py", line 310, in claim_weekly_games
    await expect(cta_btn).to_have_text("View In Cart")
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 19170, in to_have_text
    await self._impl_obj.to_have_text(
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/_impl/_assertions.py", line 481, in to_have_text
    await self._expect_impl(
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/_impl/_assertions.py", line 74, in _expect_impl
    raise AssertionError(
AssertionError: Locator expected to have text 'View In Cart'
Actual value: Add To Cart 
Call log:
LocatorAssertions.to_have_text with timeout 5000ms
  - waiting for locator("//aside//button[@data-testid='add-to-cart-cta-button']")
  -   locator resolved to <button disabled type="button" aria-label="Loading" data-testid="add-to-cart-cta-button" class="eds_14hl3lj9 eds_14hl3ljc eds_14hl3ljh eds_1ypbntdc eds_14hl3lja eds_14hl3lj2 eds_14hl3lj5">…</button>
  -   unexpected value "Add To Cart"
  -   locator resolved to <button disabled type="button" aria-label="Loading" data-testid="add-to-cart-cta-button" class="eds_14hl3lj9 eds_14hl3ljc eds_14hl3ljh eds_1ypbntdc eds_14hl3lja eds_14hl3lj2 eds_14hl3lj5">…</button>
  -   unexpected value "Add To Cart"
  -   locator resolved to <button type="button" aria-describedby="tippy-17" data-testid="add-to-cart-cta-button" class="eds_14hl3lj9 eds_14hl3ljc eds_14hl3ljh eds_1ypbntdc eds_14hl3lja eds_14hl3lj2">…</button>
  -   unexpected value "Add To Cart"
  -   locator resolved to <button type="button" aria-describedby="tippy-17" data-testid="add-to-cart-cta-button" class="eds_14hl3lj9 eds_14hl3ljc eds_14hl3ljh eds_1ypbntdc eds_14hl3lja eds_14hl3lj2">…</button>
  -   unexpected value "Add To Cart"
  -   locator resolved to <button type="button" aria-describedby="tippy-17" data-testid="add-to-cart-cta-button" class="eds_14hl3lj9 eds_14hl3ljc eds_14hl3ljh eds_1ypbntdc eds_14hl3lja eds_14hl3lj2">…</button>
  -   unexpected value "Add To Cart"
  -   locator resolved to <button type="button" aria-describedby="tippy-17" data-testid="add-to-cart-cta-button" class="eds_14hl3lj9 eds_14hl3ljc eds_14hl3ljh eds_1ypbntdc eds_14hl3lja eds_14hl3lj2">…</button>
  -   unexpected value "Add To Cart"
  -   locator resolved to <button type="button" aria-describedby="tippy-17" data-testid="add-to-cart-cta-button" class="eds_14hl3lj9 eds_14hl3ljc eds_14hl3ljh eds_1ypbntdc eds_14hl3lja eds_14hl3lj2">…</button>
  -   unexpected value "Add To Cart"
  -   locator resolved to <button type="button" aria-describedby="tippy-17" data-testid="add-to-cart-cta-button" class="eds_14hl3lj9 eds_14hl3ljc eds_14hl3ljh eds_1ypbntdc eds_14hl3lja eds_14hl3lj2">…</button>
  -   unexpected value "Add To Cart"
  -   locator resolved to <button type="button" aria-describedby="tippy-17" data-testid="add-to-cart-cta-button" class="eds_14hl3lj9 eds_14hl3ljc eds_14hl3ljh eds_1ypbntdc eds_14hl3lja eds_14hl3lj2">…</button>
  -   unexpected value "Add To Cart"

